<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class NovelSeederTambahan extends Seeder
{
    public function run()
    {
        $novels = [
            [
                'title' => 'Anak Rantau',
                'author_id' => 5,
                'category_id' => 3,
                'cover_image' => 'anak-rantau.jpg',
                'description' => 'Petualangan dan pencarian jati diri seorang anak dari perantauan.',
                'views' => 21000,
                'status' => 'completed',
            ],
            [
                'title' => 'Sabtu Bersama Bapak',
                'author_id' => 6,
                'category_id' => 1,
                'cover_image' => 'sabtu-bersama-bapak.jpg',
                'description' => 'Cerita keluarga dan warisan pesan kehidupan dari sang ayah.',
                'views' => 17000,
                'status' => 'completed',
            ],
            [
                'title' => 'Kata',
                'author_id' => 7,
                'category_id' => 4,
                'cover_image' => 'kata.jpg',
                'description' => 'Kisah romansa remaja dan perjuangan menyampaikan perasaan.',
                'views' => 31000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Nanti Kita Cerita tentang Hari Ini',
                'author_id' => 8,
                'category_id' => 1,
                'cover_image' => 'nkcthi.jpg',
                'description' => 'Kumpulan cerita dan kutipan tentang kehidupan dan keluarga.',
                'views' => 48000,
                'status' => 'completed',
            ],
            [
                'title' => 'Geez & Ann',
                'author_id' => 9,
                'category_id' => 1,
                'cover_image' => 'geez-ann.jpg',
                'description' => 'Cerita cinta dan perjuangan pasangan muda menghadapi kenyataan.',
                'views' => 26500,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Galaksi',
                'author_id' => 10,
                'category_id' => 1,
                'cover_image' => 'galaksi.jpg',
                'description' => 'Kisah remaja SMA dengan konflik cinta dan persahabatan.',
                'views' => 32500,
                'status' => 'completed',
            ],
            [
                'title' => 'Origami Hati',
                'author_id' => 11,
                'category_id' => 1,
                'cover_image' => 'origami-hati.jpg',
                'description' => 'Perjalanan menemukan cinta sejati lewat potongan kenangan.',
                'views' => 19000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'After School Club',
                'author_id' => 12,
                'category_id' => 6,
                'cover_image' => 'after-school-club.jpg',
                'description' => 'Kumpulan kisah jenaka seputar klub ekstrakurikuler sekolah.',
                'views' => 27500,
                'status' => 'completed',
            ],
            [
                'title' => 'Tereliye: Rindu',
                'author_id' => 13,
                'category_id' => 4,
                'cover_image' => 'tereliye-rindu.jpg',
                'description' => 'Novel reflektif penuh pelajaran hidup dalam perjalanan kereta api.',
                'views' => 38000,
                'status' => 'completed',
            ],
            [
                'title' => 'Hafalan Shalat Delisa',
                'author_id' => 14,
                'category_id' => 4,
                'cover_image' => 'delisa.jpg',
                'description' => 'Kisah menyentuh seorang anak perempuan korban tsunami Aceh.',
                'views' => 46000,
                'status' => 'completed',
            ],
            [
                'title' => 'Perfect Pain',
                'author_id' => 40,
                'category_id' => 1,
                'cover_image' => 'perfect-pain.jpg',
                'description' => 'Tentang luka, trauma, dan cinta yang menyembuhkan.',
                'views' => 30500,
                'status' => 'completed',
            ],
            [
                'title' => 'Balada Si Roy',
                'author_id' => 5,
                'category_id' => 3,
                'cover_image' => 'balada-roy.jpg',
                'description' => 'Petualangan Roy dalam pencarian jati diri dan cinta sejati.',
                'views' => 29500,
                'status' => 'completed',
            ],
            [
                'title' => 'Dear Nathan',
                'author_id' => 6,
                'category_id' => 1,
                'cover_image' => 'dear-nathan.jpg',
                'description' => 'Romansa SMA antara Salma dan Nathan yang penuh konflik dan harapan.',
                'views' => 41000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Konspirasi Alam Semesta',
                'author_id' => 7,
                'category_id' => 2,
                'cover_image' => 'konspirasi-alam.jpg',
                'description' => 'Kisah cinta dengan latar spionase dan idealisme politik.',
                'views' => 33000,
                'status' => 'completed',
            ],
            [
                'title' => 'Critical Love',
                'author_id' => 8,
                'category_id' => 1,
                'cover_image' => 'critical-love.jpg',
                'description' => 'Romansa dengan bumbu perbedaan prinsip dan cara pandang hidup.',
                'views' => 25000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Setengah Hati',
                'author_id' => 10,
                'category_id' => 1,
                'cover_image' => 'setengah-hati.jpg',
                'description' => 'Tentang cinta yang tak pernah benar-benar utuh.',
                'views' => 21000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Serenade Biru',
                'author_id' => 11,
                'category_id' => 6,
                'cover_image' => 'serenade-biru.jpg',
                'description' => 'Kisah masa muda yang diiringi melodi dan kenangan.',
                'views' => 26000,
                'status' => 'completed',
            ],
            [
                'title' => 'Hijrah Cinta',
                'author_id' => 12,
                'category_id' => 4,
                'cover_image' => 'hijrah-cinta.jpg',
                'description' => 'Perjalanan spiritual dalam mencari makna cinta sejati.',
                'views' => 39000,
                'status' => 'completed',
            ],
            [
                'title' => 'Negeri Para Bedebah',
                'author_id' => 13,
                'category_id' => 2,
                'cover_image' => 'bedebah.jpg',
                'description' => 'Aksi dan intrik ekonomi dalam dunia korporasi yang bengis.',
                'views' => 48000,
                'status' => 'completed',
            ],
            [
                'title' => 'Arah Langkah',
                'author_id' => 14,
                'category_id' => 4,
                'cover_image' => 'arah-langkah.jpg',
                'description' => 'Memoar perjuangan mahasiswa dengan cita dan cinta.',
                'views' => 37000,
                'status' => 'completed',
            ],
            [
                'title' => 'Garis Waktu',
                'author_id' => 40,
                'category_id' => 1,
                'cover_image' => 'garis-waktu.jpg',
                'description' => 'Perjalanan cinta yang penuh penyesalan dan harapan.',
                'views' => 29000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Bumi Manusia',
                'author_id' => 5,
                'category_id' => 3,
                'cover_image' => 'bumi-manusia.jpg',
                'description' => 'Kisah cinta dan perjuangan di masa kolonial.',
                'views' => 61000,
                'status' => 'completed',
            ],
            [
                'title' => 'Cinta di Ujung Sajadah',
                'author_id' => 6,
                'category_id' => 4,
                'cover_image' => 'cinta-sajadah.jpg',
                'description' => 'Romansa yang lahir dari doa dan pengharapan.',
                'views' => 34000,
                'status' => 'completed',
            ],
            [
                'title' => 'Aku, Kau & Sepucuk Angpau Merah',
                'author_id' => 7,
                'category_id' => 1,
                'cover_image' => 'angpau-merah.jpg',
                'description' => 'Kisah cinta lintas budaya dengan nilai keluarga yang kuat.',
                'views' => 32000,
                'status' => 'completed',
            ],
            [
                'title' => 'Madre',
                'author_id' => 8,
                'category_id' => 6,
                'cover_image' => 'madre.jpg',
                'description' => 'Tentang warisan tak terduga dan perjalanan menemukan jati diri.',
                'views' => 35500,
                'status' => 'completed',
            ],
            [
                'title' => 'Daun yang Jatuh Tak Pernah Membenci Angin',
                'author_id' => 9,
                'category_id' => 1,
                'cover_image' => 'daun-jatuh.jpg',
                'description' => 'Cinta yang tumbuh perlahan dalam diam dan pengorbanan.',
                'views' => 42000,
                'status' => 'completed',
            ],
            [
                'title' => 'Selamat Tinggal',
                'author_id' => 10,
                'category_id' => 4,
                'cover_image' => 'selamat-tinggal.jpg',
                'description' => 'Pertarungan batin dan idealisme seorang mahasiswa.',
                'views' => 27000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Balada Si Roy',
                'author_id' => 11,
                'category_id' => 3,
                'cover_image' => 'si-roy.jpg',
                'description' => 'Kisah masa remaja penuh gejolak, pemberontakan, dan pencarian jati diri.',
                'views' => 33000,
                'status' => 'completed',
            ],
            [
                'title' => 'Assalamualaikum Beijing',
                'author_id' => 12,
                'category_id' => 1,
                'cover_image' => 'assalamualaikum-beijing.jpg',
                'description' => 'Cinta dan keteguhan iman yang diuji di negeri orang.',
                'views' => 37500,
                'status' => 'completed',
            ],
            [
                'title' => 'Komet',
                'author_id' => 13,
                'category_id' => 2,
                'cover_image' => 'komet.jpg',
                'description' => 'Petualangan lintas dimensi yang penuh keajaiban dan rahasia.',
                'views' => 34000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Hafalan Shalat Delisa',
                'author_id' => 14,
                'category_id' => 4,
                'cover_image' => 'delisa.jpg',
                'description' => 'Ketegaran seorang anak menghadapi tragedi dan kehilangan.',
                'views' => 46000,
                'status' => 'completed',
            ],
            [
                'title' => 'Twivortiare',
                'author_id' => 5,
                'category_id' => 1,
                'cover_image' => 'twivortiare.jpg',
                'description' => 'Drama rumah tangga penuh cinta, emosi, dan Twitter.',
                'views' => 39000,
                'status' => 'completed',
            ],
            [
                'title' => 'Sabtu Bersama Bapak',
                'author_id' => 6,
                'category_id' => 4,
                'cover_image' => 'sabtu-bapak.jpg',
                'description' => 'Pesan-pesan kehidupan dari seorang ayah yang abadi lewat video.',
                'views' => 31000,
                'status' => 'completed',
            ],
            [
                'title' => 'Bidadari Bermata Bening',
                'author_id' => 7,
                'category_id' => 1,
                'cover_image' => 'bidadari-bening.jpg',
                'description' => 'Romansa Islami yang lembut dan penuh makna.',
                'views' => 28000,
                'status' => 'completed',
            ],
            [
                'title' => 'Aroma Karsa',
                'author_id' => 8,
                'category_id' => 2,
                'cover_image' => 'aroma-karsa.jpg',
                'description' => 'Misteri aroma yang membawa penciuman menjadi senjata dan kutukan.',
                'views' => 44000,
                'status' => 'completed',
            ],
            [
                'title' => 'Perempuan Berkalung Sorban',
                'author_id' => 9,
                'category_id' => 4,
                'cover_image' => 'sorban.jpg',
                'description' => 'Kisah perjuangan perempuan dalam kungkungan tradisi patriarki.',
                'views' => 25000,
                'status' => 'completed',
            ],
            [
                'title' => 'Cinta di Ujung Sajadah',
                'author_id' => 10,
                'category_id' => 1,
                'cover_image' => 'ujung-sajadah.jpg',
                'description' => 'Romansa dan spiritualitas yang bertemu di ujung doa.',
                'views' => 30500,
                'status' => 'completed',
            ],
            [
                'title' => 'Geez & Ann',
                'author_id' => 11,
                'category_id' => 1,
                'cover_image' => 'geez-ann.jpg',
                'description' => 'Kisah cinta remaja yang manis namun rumit.',
                'views' => 36000,
                'status' => 'completed',
            ],
            [
                'title' => 'Matahari',
                'author_id' => 12,
                'category_id' => 2,
                'cover_image' => 'matahari.jpg',
                'description' => 'Petualangan luar biasa dalam dunia paralel dan penuh rahasia.',
                'views' => 41500,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Hati Suhita',
                'author_id' => 13,
                'category_id' => 1,
                'cover_image' => 'hati-suhita.jpg',
                'description' => 'Romansa dalam dunia pesantren yang penuh konflik batin.',
                'views' => 42000,
                'status' => 'completed',
            ],
            [
                'title' => 'Jingga dan Senja',
                'author_id' => 14,
                'category_id' => 1,
                'cover_image' => 'jingga-senja.jpg',
                'description' => 'Kisah cinta masa SMA dengan dinamika yang menggemaskan.',
                'views' => 28500,
                'status' => 'completed',
            ],
            [
                'title' => 'Di Tanah Lada',
                'author_id' => 5,
                'category_id' => 4,
                'cover_image' => 'tanah-lada.jpg',
                'description' => 'Anak-anak yang belajar tentang hidup dari kerasnya kenyataan.',
                'views' => 24000,
                'status' => 'completed',
            ],
            [
                'title' => 'Milea: Suara dari Dilan',
                'author_id' => 6,
                'category_id' => 1,
                'cover_image' => 'milea.jpg',
                'description' => 'Sudut pandang Dilan tentang kisah cinta yang tak terlupakan.',
                'views' => 41000,
                'status' => 'completed',
            ],
            [
                'title' => 'Winter in Tokyo',
                'author_id' => 7,
                'category_id' => 1,
                'cover_image' => 'winter-tokyo.jpg',
                'description' => 'Cinta yang tumbuh dalam dinginnya musim dingin Tokyo.',
                'views' => 35000,
                'status' => 'completed',
            ],
        ];
        
        foreach ($novels as $novel) {
            $this->db->table('novels')->insert([
                'title' => $novel['title'],
                'author_id' => $novel['author_id'],
                'category_id' => $novel['category_id'],
                'cover_image' => $novel['cover_image'],
                'description' => $novel['description'],
                'views' => $novel['views'],
                'status' => $novel['status'],
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]);
        }
        
    }
}
