<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class NovelSeeder extends Seeder
{
    public function run()
    {
        $novels = [
            [
                'title' => 'Dilan 1990',
                'author_id' => 5,
                'category_id' => 1,
                'cover_image' => 'dilan.jpg',
                'description' => 'Kisah cinta remaja di Bandung antara Milea dan Dilan.',
                'views' => 25000,
                'status' => 'completed',
            ],
            [
                'title' => 'Bumi',
                'author_id' => 6,
                'category_id' => 2,
                'cover_image' => 'bumi.jpg',
                'description' => 'Petualangan anak Indigo bernama Raib di dunia paralel bernama Tarsis.',
                'views' => 30000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Negeri 5 Menara',
                'author_id' => 7,
                'category_id' => 3,
                'cover_image' => 'negeri5menara.jpg',
                'description' => 'Perjuangan para santri mengejar mimpi dari pondok pesantren.',
                'views' => 18000,
                'status' => 'completed',
            ],
            [
                'title' => 'Ayat-Ayat Cinta',
                'author_id' => 8,
                'category_id' => 1,
                'cover_image' => 'ayat-ayat-cinta.jpg',
                'description' => 'Kisah cinta Fahri dengan latar Mesir dan nilai-nilai Islam.',
                'views' => 45000,
                'status' => 'completed',
            ],
            [
                'title' => 'Danur',
                'author_id' => 9,
                'category_id' => 5,
                'cover_image' => 'danur.jpg',
                'description' => 'Cerita horor berdasarkan pengalaman Risa Saraswati bersama teman hantu Belandanya.',
                'views' => 22000,
                'status' => 'completed',
            ],
            [
                'title' => 'Cinta Brontosaurus',
                'author_id' => 10,
                'category_id' => 6,
                'cover_image' => 'cinta-brontosaurus.jpg',
                'description' => 'Kumpulan kisah cinta absurd dan lucu karya Raditya Dika.',
                'views' => 37000,
                'status' => 'completed',
            ],
            [
                'title' => 'Rembulan Tenggelam di Wajahmu',
                'author_id' => 40,
                'category_id' => 4,
                'cover_image' => 'rembulan.jpg',
                'description' => 'Kisah spiritual dan pencarian makna hidup.',
                'views' => 20000,
                'status' => 'completed',
            ],
            [
                'title' => 'Limerence',
                'author_id' => 40,
                'category_id' => 4,
                'cover_image' => 'limerence.jpg',
                'description' => 'Kisah spiritual dan pencarian makna hidup.',
                'views' => 52512,
                'status' => 'completed',
            ],
            [
                'title' => 'Evanescent',
                'author_id' => 40,
                'category_id' => 4,
                'cover_image' => 'evanescent.jpg',
                'description' => 'Kisah spiritual dan pencarian makna hidup.',
                'views' => 52512,
                'status' => 'completed',
            ],
            [
                'title' => 'The Broken Marriage',
                'author_id' => 40,
                'category_id' => 4,
                'cover_image' => 'TBM.jpg',
                'description' => 'Kisah spiritual dan pencarian makna hidup.',
                'views' => 52512,
                'status' => 'completed',
            ],
            [
                'title' => 'Surat Kecil untuk Tuhan',
                'author_id' => 11,
                'category_id' => 4,
                'cover_image' => 'surat-kecil.jpg',
                'description' => 'Perjuangan seorang gadis kecil melawan kanker dengan penuh harapan dan cinta.',
                'views' => 31000,
                'status' => 'completed',
            ],
            [
                'title' => 'Critical Eleven',
                'author_id' => 12,
                'category_id' => 1,
                'cover_image' => 'critical-eleven.jpg',
                'description' => 'Tentang 11 menit paling menentukan dalam pertemuan dua insan di pesawat.',
                'views' => 26500,
                'status' => 'completed',
            ],
            [
                'title' => 'Perahu Kertas',
                'author_id' => 13,
                'category_id' => 1,
                'cover_image' => 'perahu-kertas.jpg',
                'description' => 'Kisah Kugy dan Keenan mencari jati diri dan cinta di antara mimpi-mimpi besar.',
                'views' => 39000,
                'status' => 'completed',
            ],
            [
                'title' => 'Pulang',
                'author_id' => 14,
                'category_id' => 4,
                'cover_image' => 'pulang.jpg',
                'description' => 'Novel epik tentang pengasingan, cinta tanah air, dan perjuangan hidup seorang eksil.',
                'views' => 24000,
                'status' => 'completed',
            ],
            [
                'title' => 'Supernova: Ksatria, Puteri, dan Bintang Jatuh',
                'author_id' => 5,
                'category_id' => 2,
                'cover_image' => 'supernova.jpg',
                'description' => 'Perpaduan sains, spiritualitas, dan cinta yang membentuk jalinan kisah multisemesta.',
                'views' => 43000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Tenggelamnya Kapal Van Der Wijck',
                'author_id' => 6,
                'category_id' => 1,
                'cover_image' => 'kapal-vdw.jpg',
                'description' => 'Cinta Zainuddin dan Hayati yang karam oleh perbedaan adat dan status sosial.',
                'views' => 48000,
                'status' => 'completed',
            ],
            [
                'title' => 'Hujan',
                'author_id' => 7,
                'category_id' => 4,
                'cover_image' => 'hujan.jpg',
                'description' => 'Tentang cinta, kehilangan, dan pengorbanan dalam dunia yang tak lagi sama.',
                'views' => 29500,
                'status' => 'completed',
            ],
            [
                'title' => 'London: Angel',
                'author_id' => 8,
                'category_id' => 1,
                'cover_image' => 'london-angel.jpg',
                'description' => 'Perjalanan hidup dan cinta Angel di kota London yang penuh cerita.',
                'views' => 17500,
                'status' => 'completed',
            ],
            [
                'title' => 'Radikus Makankakus',
                'author_id' => 9,
                'category_id' => 6,
                'cover_image' => 'radikus.jpg',
                'description' => 'Kumpulan kisah kocak Raditya Dika tentang kehidupan sehari-hari yang absurd.',
                'views' => 31000,
                'status' => 'completed',
            ],
            [
                'title' => 'Gerbang Dialog Danur',
                'author_id' => 10,
                'category_id' => 5,
                'cover_image' => 'dialog-danur.jpg',
                'description' => 'Kisah Risa Saraswati tentang pertemuan dengan makhluk tak kasat mata dan kisah masa lalu mereka.',
                'views' => 27000,
                'status' => 'ongoing',
            ],
            [
                'title' => 'Laskar Pelangi',
                'author_id' => 11,
                'category_id' => 3,
                'cover_image' => 'laskar-pelangi.jpg',
                'description' => 'Kisah anak-anak miskin di Belitung yang penuh semangat dalam meraih pendidikan.',
                'views' => 50000,
                'status' => 'completed',
            ],
            [
                'title' => 'Garis Waktu',
                'author_id' => 12,
                'category_id' => 1,
                'cover_image' => 'garis-waktu.jpg',
                'description' => 'Kumpulan puisi dan cerita pendek tentang cinta, luka, dan waktu.',
                'views' => 23000,
                'status' => 'completed',
            ],
            [
                'title' => 'Sebuah Seni untuk Bersikap Bodo Amat',
                'author_id' => 13,
                'category_id' => 4,
                'cover_image' => 'bodo-amat.jpg',
                'description' => 'Panduan hidup dengan jujur, realistis, dan fokus pada hal penting.',
                'views' => 52000,
                'status' => 'completed',
            ],            
        ];

        foreach ($novels as $novel) {
            $this->db->table('novels')->insert([
                'title' => $novel['title'],
                'author_id' => $novel['author_id'],
                'category_id' => $novel['category_id'],
                'cover_image' => $novel['cover_image'],
                'description' => $novel['description'],
                'views' => $novel['views'],
                'status' => $novel['status'],
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]);
        }
    }
}
